#!/usr/bin/env bash

display () {
  dig +short "${2}.${1}" | awk '{print "The subdomain '"$2"' is a A record and points to " $1}'
}

if [ "$#" -eq 1 ]
then
  subdms=("www" "lb-01" "web-01" "web-02")
  for subd in "${subdms[@]}"
  do
    display "$1" "$subd"
  done
elif [ "$#" -eq 2 ]
then
  display "$1" "$2"
else
  echo "Usage: $0 <domain> <subdomain>"
fi

