#!/usr/bin/env bash
# a Bash script that configures a new Ubuntu machine 

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
