#!/usr/bin/env bash
# write a Bash script that configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install haproxy

# backing up haproxy config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT

frontend http-in
    bind *:80
    default_backend my_servers

backend my_servers
    balance roundrobin
    server web-01 54.89.50.120:80 check
    server web-02 54.237.95.28:80 check

EOT

# start HAProxy
sudo /etc/init.d/haproxy start

# set HAProxy to start on boot
sudo update-rc.d haproxy default

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
