#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive out of it.

# Get today's date in the required format
date=$(date +"%d-%m-%Y")

# Set the name of the backup file and archive
backup_file="backup.sql"
archive_name="$date.tar.gz"

# Dump all MySQL databases into backup.sql using root user and specified password
mysqldump -u root -p"$1" --all-databases > "$backup_file"

# Compress the backup file into a tar.gz archive
tar -czvf "$archive_name" "$backup_file"

# Remove the original backup file
# rm "$backup_file"
